Adding example in readme
defenseunicorns/terraform-aws-tfstate-backend pull request #32
Opened 2023-02-27 22:07 UTC by wirewc

Closes #22. 

Adds example to README and adds a little bit more documentation.

2023-02-27 22:07 UTC, wirewc commented
/test all

2023-02-27 22:31 UTC, RothAndrew commented on README.md
> +# Getting Started
Markdown docs should only have 1 H1. Recommend making this an H2 instead.

2023-02-27 22:31 UTC, RothAndrew commented on README.md
> +Ensure Terraform is available on the local system and that the AWS CLI has the appropriate credentials put in place.
If I play dumb for a minute and think about what I still need from this Getting Started guide, from this I get what the dependencies are, but I'm still missing:

* How do I take this and use it in my own project?
* What do I need to do after I've run my first `terraform apply` so that this infrastructure is also tracked in my new remote state backend? (`terraform init -force-copy`)

Something similar to the [Usage section in CloudPosse's similar module](https://github.com/cloudposse/terraform-aws-tfstate-backend#usage) is what is going through my head at the moment

2023-02-27 22:31 UTC, RothAndrew commented on README.md
> +
Do we need this stuff here? Or is it just taking up space? This stuff will be in the actual example in the examples folder. I don't see it providing much value to be here as well.

2023-02-27 22:31 UTC, RothAndrew commented on README.md
> +  source = "git::https://github.com/defenseunicorns/terraform-aws-tfstate-backend.git?ref=main"
Instead of `?ref=main` can we say something like `?ref=x.x.x`? I fear that people may copy-paste this, and we want to avoid any appearance of thinking people should use `main` as a best practice.

2023-02-27 22:31 UTC, RothAndrew commented on README.md
> +}
I'm not familiar with this pattern of providing the whole module as an output. What is this for?

2023-02-27 23:14 UTC, wirewc commented on README.md
> +# Getting Started
Using only H2's reduces navigability. A title should not be defined with an H1 exclusively. I have never seen a recommendation of that practice before. 

I will look up if there is a style guide within Defense Unicorns that I may have missed.

2023-02-27 23:16 UTC, wirewc commented on README.md
> +
Example was placed here based on ideal usability patterns. However I do see how it is redundant with the examples directly. Reason why I felt it might be worth highlighting is because the examples folder does not show how a module should look. When dealing with easy installations, you want to encourage as much copying and pasting as possible.

2023-02-27 23:17 UTC, wirewc commented on README.md
> +  source = "git::https://github.com/defenseunicorns/terraform-aws-tfstate-backend.git?ref=main"
I agree, we just have not released a tagged version yet. This is a cart/horse situation.

2023-02-27 23:18 UTC, RothAndrew commented on README.md
> +  source = "git::https://github.com/defenseunicorns/terraform-aws-tfstate-backend.git?ref=main"
v0.0.1 is released

2023-02-27 23:19 UTC, RothAndrew commented on README.md
> +  source = "git::https://github.com/defenseunicorns/terraform-aws-tfstate-backend.git?ref=main"
but, i'm saying we should use the literal string `x.x.x`, not any particular tagged version

2023-02-27 23:19 UTC, RothAndrew commented on README.md
> +  source = "git::https://github.com/defenseunicorns/terraform-aws-tfstate-backend.git?ref=main"
or `x.y.z` or `a.b.c` or whatever makes sense that looks like a version but isn't

2023-02-27 23:25 UTC, RothAndrew commented on README.md
> +# Getting Started
I don't have a problem if you want to keep it the way it is.

2023-02-27 23:29 UTC, RothAndrew commented on README.md
> +
What if, instead of this stuff, we added a small note "for a complete example, see here" that points at the example?

2023-02-27 23:30 UTC, RothAndrew requested changes
Hard issues for me are not using `main` in the version ref and adding a bit more to the getting started guide. The other stuff is more nitpicky that I don't have big issues with.

2023-02-28 01:33 UTC, wirewc commented on README.md
> +Ensure Terraform is available on the local system and that the AWS CLI has the appropriate credentials put in place.
Moved the example, I understand the model better now. I'm not fully in agreement but it is an established pattern that has a following.

2023-02-28 14:19 UTC, wirewc commented on README.md
> +  source = "git::https://github.com/defenseunicorns/terraform-aws-tfstate-backend.git?ref=main"
I see, you're correct. I removed it but in the future I make sure to base it off of a version as that is best practice. Thank you!

2023-02-28 14:20 UTC, wirewc commented
/test all

2023-02-28 16:11 UTC, wirewc commented
/test all

2023-02-28 16:40 UTC, RothAndrew requested changes

2023-02-28 16:40 UTC, RothAndrew commented on examples/complete/README.md
> +1. Delete with `terraform delete`
```suggestion
1. Delete with `terraform destroy`
```

2023-02-28 16:40 UTC, RothAndrew commented on examples/complete/README.md
> +Standard Terraform Workflow$
```suggestion
Standard Terraform Workflow
```

2023-02-28 16:40 UTC, RothAndrew commented on examples/complete/README.md
> +1. Checkout this code.$
```suggestion
1. Checkout this code.
```

2023-02-28 17:52 UTC, wirewc commented on examples/complete/README.md
> +Standard Terraform Workflow$
Added, thanks!

2023-02-28 18:24 UTC, RothAndrew approved these changes

2023-02-28 18:24 UTC, merged