Initial commit of the contributing guidelines
defenseunicorns/terraform-aws-tfstate-backend pull request #47
Opened 2023-04-25 18:36 UTC by wirewc

Creating a first attempt of a contributing document as required by #10.

2023-04-25 18:38 UTC, RothAndrew commented
The original plan had been to link to [this document](https://github.com/defenseunicorns/uds-infra/blob/main/CONTRIBUTING.md) rather than having a separate contributor guide.

Not saying that can't change, just providing context on what had been discussed previously.

2023-04-25 18:43 UTC, bdfinst reviewed
Should probably have information about how to test changes.

2023-04-25 18:43 UTC, bdfinst commented on CONTRIBUTING.md
> +* Major changes require a document of context using ADRs. Please see [ADR Manager](https://github.com/adr/adr-manager) for how to create an ADR (see ADR folder).
What's a "major change?"

2023-04-25 18:43 UTC, bdfinst commented on CONTRIBUTING.md
> +* Codeowners and project members only have the ability to run the `/test all` command inside of a merge reqest.
Why is testing limited?

2023-04-25 18:46 UTC, wirewc commented on CONTRIBUTING.md
> +* Codeowners and project members only have the ability to run the `/test all` command inside of a merge reqest.
@RothAndrew wasn't there a reason why we wanted to limit testing with IaC? I believe it was due to protecting secrets.

2023-04-25 18:48 UTC, wirewc commented on CONTRIBUTING.md
> +* Major changes require a document of context using ADRs. Please see [ADR Manager](https://github.com/adr/adr-manager) for how to create an ADR (see ADR folder).
I guess I should rephrase the language to something inline with something that requires an ADR.

2023-04-25 18:51 UTC, RothAndrew commented on CONTRIBUTING.md
> +* Codeowners and project members only have the ability to run the `/test all` command inside of a merge reqest.
Since running the tests causes real AWS infrastructure to be created, which costs real money, we have to inspect the changes that a PR is making before allowing the changes to be tested. This is the current way to do that. The rules in place are that you are allowed to trigger the tests if you have been listed as a collaborator on the repo with at least "write" access.

This is a well established pattern when maintaining open source Infrastructure as Code whose tests deploy to real cloud accounts that cost real money.

2023-04-25 19:39 UTC, wirewc commented
@RothAndrew and @bdfinst the contributing guidelines was copied from something Andy originally wrote that I think is valuable for reuse. Please evaluate with fresh eyes since the changes are significant.

2023-04-25 20:52 UTC, lucasrod16 approved these changes
LGTM. I'm sure we will evolve and iterate on things, but I think this captures current state well.

2023-04-26 18:32 UTC, bdfinst commented
Didn't we decide to link to a central CONTRIBUTOR page in the README?

2023-04-26 18:34 UTC, bdfinst requested changes
Suggest we remove this file and add a link in the README to the main file here: https://github.com/defenseunicorns/uds-infra/blob/main/CONTRIBUTING.md

2023-04-26 18:36 UTC, bdfinst commented
/test all

2023-04-26 19:53 UTC, wirewc commented
@bdfinst @RothAndrew where do we put the central page to be? I agree but... where? Should it be in the `uds` project or `uds-infra`?

2023-04-26 20:52 UTC, RothAndrew commented
I have no strong feelings about where it should go.

2023-04-27 12:32 UTC, bdfinst commented
/test e3e

2023-04-27 12:38 UTC, bdfinst commented
/test e3e

2023-04-27 12:40 UTC, bdfinst commented
/test e2e

2023-04-27 13:03 UTC, bdfinst commented
/test-exp e3e

2023-04-27 13:25 UTC, bdfinst commented
/test-exp e3e

2023-04-27 13:36 UTC, bdfinst commented
/test-exp e3e

2023-04-27 13:37 UTC, bdfinst commented
/test e3e

2023-05-02 15:24 UTC, wirewc commented
Closing now. However the next iteration of the contributing document should just point to the contributing document when this issue https://github.com/defenseunicorns/uds/issues/65 is resolved.

2023-05-02 17:06 UTC, merged